# Generated by Django 4.2.19 on 2026-04-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0001_initial'),
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='emprunt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='emprunt.emprunt'),
        ),
    ]
