# Generated by Django 6.0.3 on 2026-05-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_equipement_emprunt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='emprunt',
        ),
    ]
