# Generated by Django 6.0.3 on 2026-06-12 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0003_remove_equipement_emprunt'),
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='salles.salle', verbose_name='Salle'),
        ),
    ]
