# Generated by Django 4.2.19 on 2026-04-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_alter_contact_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_dmd', models.CharField(max_length=50)),
                ('date_empr', models.DateField(auto_now_add=True)),
                ('date_retour_prevu', models.DateField()),
                ('date_retour_effect', models.DateField(blank=True, null=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
        ),
    ]
