# Generated by Django 6.0.3 on 2026-05-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0009_emprunt_message_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_empr',
            field=models.DateField(),
        ),
    ]
