# Generated by Django 5.2.13 on 2026-04-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire', models.CharField(max_length=100)),
                ('equipement', models.CharField(max_length=100)),
                ('motif', models.TextField()),
                ('date_emprunt', models.DateField()),
                ('date_retour', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
            ],
        ),
    ]
