# Generated by Django 6.0.3 on 2026-04-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(choices=[('Admin', 'Administrateur'), ('Gest', 'Gestionnaire')], default='Gestionnaire', max_length=50),
        ),
    ]
