# Generated by Django 6.0.3 on 2026-04-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0002_utilisateur_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='statut',
            new_name='role',
        ),
    ]
