# Generated by Django 6.0.3 on 2026-05-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_salle', models.CharField(choices=[('laboratoire', 'Laboratoire'), ('salle_cours', 'Salle de cours'), ('atelier', 'Atelier'), ('bureau', 'Bureau'), ('stock', 'Stock / Réserve'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('capacite', models.PositiveIntegerField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'ordering': ['nom'],
            },
        ),
    ]
