# Generated by Django 5.2.13 on 2026-04-14 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('emprunte', 'Emprunté'), ('maintenance', 'En maintenance'), ('retire', 'Retiré')], default='disponible', max_length=20)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipements/')),
                ('est_actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='equipements.categorie')),
            ],
            options={
                'verbose_name': 'Équipement',
                'ordering': ['nom'],
            },
        ),
    ]
