# Generated by Django 6.0.4 on 2026-04-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='etat',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Planifié', 'Planifié'), ('Validé', 'Validé'), ('Retourné', 'Retourné'), ('Expiré', 'Expiré'), ('Annulé', 'Annulé')], default='En cours', max_length=90),
        ),
    ]
