# Generated by Django 6.0.3 on 2026-05-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0003_equipement_emprunt_equipement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='equipement',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='equipements',
            field=models.ManyToManyField(blank=True, related_name='emprunts', to='emprunt.equipement'),
        ),
    ]
