# Generated by Django 6.0.3 on 2026-05-03 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0004_remove_emprunt_equipement_emprunt_equipements'),
        ('equipements', '0003_remove_equipement_emprunt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='equipements',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='equipement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipements.equipement'),
        ),
    ]
