# Generated by Django 6.0.3 on 2026-05-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0005_remove_emprunt_equipements_emprunt_equipement'),
        ('equipements', '0003_remove_equipement_emprunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='equipements.equipement'),
        ),
    ]
