# Generated by Django 6.0.3 on 2026-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0006_alter_emprunt_equipement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='etat',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('PLANIFIE', 'Planifié'), ('VALIDE', 'Validé'), ('RETOURNE', 'Retourné'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='En cours', max_length=90),
        ),
    ]
