# Generated by Django 6.0.3 on 2026-05-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0007_alter_emprunt_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='etat',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('PLANIFIE', 'Planifié'), ('VALIDE', 'Validé'), ('RETOURNE', 'Retourné'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé'), ('REFUSE', 'Refusé')], default='EN_COURS', max_length=20),
        ),
    ]
