# Generated by Django 6.0.3 on 2026-05-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunt', '0008_alter_emprunt_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='message_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
