# Generated by Django 6.0.3 on 2026-06-12 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_matricule'),
        ('emprunt', '0010_alter_emprunt_date_empr'),
        ('equipements', '0003_remove_equipement_emprunt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('entree', 'Entrée'), ('emprunt', 'Emprunt'), ('sortie', 'Sortie')], default='emprunt', max_length=20, verbose_name="Type d'opération")),
                ('date_operation', models.DateField(verbose_name="Date de l'opération")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('objet_demande', models.CharField(blank=True, max_length=200, verbose_name='Objet de la demande')),
                ('date_retour_prevu', models.DateField(blank=True, null=True, verbose_name='Date retour prévue')),
                ('date_retour_effectif', models.DateField(blank=True, null=True, verbose_name='Date retour effective')),
                ('message_admin', models.TextField(blank=True, null=True, verbose_name='Message administrateur')),
                ('etat', models.CharField(choices=[('EN_COURS', 'En cours'), ('PLANIFIE', 'Planifié'), ('VALIDE', 'Validé'), ('RETOURNE', 'Retourné'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé'), ('REFUSE', 'Refusé')], default='EN_COURS', max_length=20, verbose_name='État')),
                ('destination', models.CharField(blank=True, choices=[('eyang', 'Campus Eyang'), ('autre', 'Autre')], max_length=50, null=True, verbose_name='Destination')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='Bénéficiaire')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='equipements.equipement', verbose_name='Équipement')),
                ('gestionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_geres', to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaire')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
                'ordering': ['-date_operation'],
            },
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='beneficiaire',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='equipement',
        ),
        migrations.DeleteModel(
            name='Equipement',
        ),
        migrations.DeleteModel(
            name='Emprunt',
        ),
    ]
