# Generated by Django 5.2.13 on 2026-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('type_contact', models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('personnel', 'Personnel'), ('externe', 'Externe')], default='etudiant', max_length=20)),
                ('matricule', models.CharField(blank=True, max_length=50)),
                ('filiere', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
