# Generated by Django 4.2.19 on 2026-04-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
