# Generated by Django 6.0.3 on 2026-06-12 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_matricule'),
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='salles.salle', verbose_name='Salle de classe'),
        ),
    ]
