# Generated by Django 6.0.3 on 2026-06-12 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0004_equipement_salle'),
        ('salles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, verbose_name='Description / Contexte')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('cloture', 'Clôturé')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('endommage', 'Endommagé')], default='present', max_length=20, verbose_name='Statut constaté')),
                ('quantite_attendue', models.PositiveIntegerField(default=1, verbose_name='Quantité attendue')),
                ('quantite_constatee', models.PositiveIntegerField(default=0, verbose_name='Quantité constatée')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_verification', models.DateTimeField(auto_now=True, verbose_name='Date de vérification')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_inventaire', to='equipements.equipement', verbose_name='Équipement')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventaire.inventaire', verbose_name='Inventaire')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_inventaire', to='salles.salle', verbose_name='Salle')),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_verifiees', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'ordering': ['salle', 'equipement'],
                'unique_together': {('inventaire', 'salle', 'equipement')},
            },
        ),
    ]
